### PR TITLE
Add dependencies section to pyproject.toml

### PR DESCRIPTION
**Pull request by afuetterer**
Hi @dfreelon,

thank you for this project. This is my first PR, so feel free to adapt, close or discuss, however you see fit.

A friend of mine recently ran into the same issue, as described in #25.

I tried to reproduce the behavior.

I installed the project with
```
pip install pyktok
```

Running
```python
>>> import pyktok as pyk
```

threw this error:

```python
>>> import pyktok as pyk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "***/.venv/lib/python3.11/site-packages/pyktok/__init__.py", line 1, in <module>
    from .pyktok import *
  File "***.venv/lib/python3.11/site-packages/pyktok/pyktok.py", line 8, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'
```

## Proposed Changes

So I propose the following changes:

- add the requirements in the dependencies section of `pyproject.toml`, as per https://hatch.pypa.io/latest/config/dependency/
- add a minimal test case to import the library, using pytest
- run the test case in github actions
- add a .gitignore file to ignore pycache from version control

What do you think?

You will find the error mentioned in #25 in the github actions log.

### CODE REVIEW

**Comment by afuetterer** [comment]
You need to pin webdriver-manager to 3.9.0, because `ChromeType` is missing from 3.9.1 onwards.
Or you refactor using Chrome, instead of ChromeType, when using webdriver-manager > 3.9.0.

Let me know what you think.

**Comment by afuetterer** [comment]
Is this no good?

**Comment by dfreelon** [comment]
Apologies, I've been busy with other projects. Let me look into this and get back to you. In the meantime, feel free to fork your own version.

**Comment by afuetterer** [comment]
No problem. Please let me know what you think, when you have the time.

**Comment by afuetterer** [comment]
Closing this due to inactivity.

**Comment by dfreelon** [comment]
Hi, I wanted to follow up on this and apologize--time got away from me to address it and I also didn't understand the distinction between `requires` and `dependencies` in `pyproject.toml` as this was my first time using hatchling. Anyway, I corrected the `pyproject.toml` but didn't add all the test material since I'm not sure it would work given all the changes to pyktok since this was added. Thanks again for bringing this to my attention and I regret leaving it unattended for so long.

**Pull request closed without merging**
